### ISSUE TITLE
Crash when trying to scrub.

### ISSUE THREAD

**Issue by skorokithakis** [NSinopoli/lucido#2]
When trying to scrub data with the example config, I get the following crash:

~~~python
20:07:54 $ luci -s
Scrubbing sensitive data...
Traceback (most recent call last):
  File "/home/stavros/.local/bin/luci", line 11, in <module>
    sys.exit(main())
  File "/home/stavros/.local/lib/python3.5/site-packages/lucido/main.py", line 285, in main
    scrub_sensitive_data(config)
  File "/home/stavros/.local/lib/python3.5/site-packages/lucido/main.py", line 168, in scrub_sensitive_data
    config = update_replacements(config)
  File "/home/stavros/.local/lib/python3.5/site-packages/lucido/main.py", line 211, in update_replacements
    path, original = line.rstrip().split(':', 1)
ValueError: not enough values to unpack (expected 2, got 1)
~~~

**Comment by NSinopoli** [comment]
Hi, thanks for your bug report. Unfortunately, I can't reproduce this, so hopefully we can narrow it down.

In my working directory is the file `luci.yml`, and here are its contents:

```
exclude:
- .git
sensitive:
- qqhPKzffeZu0
- ALpeJmcMs7TG
- z-1JWjRdbXzN
- 3r_h1q_1TEs3
```

**Python:** v3.6.1
**Grep:** GNU grep 3.0

Let me know how your setup differs from mine and we'll take it from there.

**Comment by skorokithakis** [comment]
Ah, I'm afraid I scrubbed the repo with bfg and then deleted it, and now that I tried to clone it again and reproduce it, the problem is no longer there. It seems that grep just returned some line that wasn't a match, and that made lucido crash. Feel free to close this, as I can't reproduce it, or add an exception around the split just in case grep can't find the line or something...
